# Generated by Django 5.1.1 on 2024-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_event_end_date_remove_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_positions', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('education_qualification', models.CharField(max_length=255)),
                ('required_experience', models.CharField(max_length=255)),
                ('preferred_gender', models.CharField(max_length=50)),
                ('travelling', models.CharField(max_length=50)),
                ('apply_by', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
