# Generated by Django 5.1.1 on 2024-11-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='No title.', max_length=200),
        ),
    ]
