# Generated by Django 5.1.1 on 2024-11-18 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_hours', models.PositiveIntegerField()),
                ('offered_in', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_hours', models.PositiveIntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='sms.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.teacher')),
            ],
        ),
    ]
