# Generated by Django 5.1.1 on 2024-11-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_offeredsubject_semestercurriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='semestercurriculum',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='semestercurriculum',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='semestercurriculum',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.AlterField(
            model_name='semesteractivity',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='semester',
            name='school_year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='sms.schoolyear'),
        ),
        migrations.DeleteModel(
            name='OfferedSubject',
        ),
        migrations.DeleteModel(
            name='SemesterCurriculum',
        ),
    ]
