# Generated by Django 5.1.1 on 2024-11-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_curriculum_remove_semester_school_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='2024', max_length=50)),
                ('image', models.ImageField(upload_to='curriculum_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='image',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='sms.grade'),
        ),
    ]
