# Generated by Django 5.1.1 on 2024-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_alter_student_user_alter_teacher_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='Computer Science', max_length=50),
        ),
    ]
