# Generated by Django 5.1.1 on 2024-11-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='Subject',
        ),
    ]
