# Generated by Django 5.1.1 on 2024-11-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_rename_department_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='class_instance',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classsubject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='student',
        ),
        migrations.RemoveField(
            model_name='offeredsubject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='offeredsubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sms.grade'),
        ),
        migrations.CreateModel(
            name='TeacherGradeCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_teacher_grades', to='sms.curriculum')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_teacher_curriculums', to='sms.grade')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grade_curriculums', to='sms.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'grade', 'curriculum')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassSubject',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamResult',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='OfferedSubject',
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
