# Generated by Django 5.1.1 on 2024-11-24 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_remove_exam_class_instance_remove_fee_class_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_present', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sms.student')),
                ('teacher_grade_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sms.teachergradecurriculum')),
            ],
        ),
    ]
