# Generated by Django 5.1.1 on 2024-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0021_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='total_classes',
            field=models.IntegerField(default=12),
        ),
    ]
