# Generated by Django 5.1.1 on 2024-11-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_curriculum_total_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='remaining_attendance',
            field=models.IntegerField(default=10),
        ),
    ]
