# Generated by Django 5.1.1 on 2024-11-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_curriculum_remaining_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='remaining_attendance',
            field=models.IntegerField(default=12),
        ),
    ]
